// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v2/feed_api.proto

package protov2

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListMessagesRequest struct {
	FeedId               string   `protobuf:"bytes,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMessagesRequest) Reset()         { *m = ListMessagesRequest{} }
func (m *ListMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*ListMessagesRequest) ProtoMessage()    {}
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c9e0934360152fa, []int{0}
}

func (m *ListMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMessagesRequest.Unmarshal(m, b)
}
func (m *ListMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMessagesRequest.Marshal(b, m, deterministic)
}
func (m *ListMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMessagesRequest.Merge(m, src)
}
func (m *ListMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_ListMessagesRequest.Size(m)
}
func (m *ListMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMessagesRequest proto.InternalMessageInfo

func (m *ListMessagesRequest) GetFeedId() string {
	if m != nil {
		return m.FeedId
	}
	return ""
}

type ListMessagesResponse struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMessagesResponse) Reset()         { *m = ListMessagesResponse{} }
func (m *ListMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*ListMessagesResponse) ProtoMessage()    {}
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c9e0934360152fa, []int{1}
}

func (m *ListMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMessagesResponse.Unmarshal(m, b)
}
func (m *ListMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMessagesResponse.Marshal(b, m, deterministic)
}
func (m *ListMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMessagesResponse.Merge(m, src)
}
func (m *ListMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_ListMessagesResponse.Size(m)
}
func (m *ListMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMessagesResponse proto.InternalMessageInfo

func (m *ListMessagesResponse) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*ListMessagesRequest)(nil), "proto.v2.ListMessagesRequest")
	proto.RegisterType((*ListMessagesResponse)(nil), "proto.v2.ListMessagesResponse")
}

func init() { proto.RegisterFile("v2/feed_api.proto", fileDescriptor_0c9e0934360152fa) }

var fileDescriptor_0c9e0934360152fa = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x33, 0xd2, 0x4f,
	0x4b, 0x4d, 0x4d, 0x89, 0x4f, 0x2c, 0xc8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00,
	0x53, 0x7a, 0x65, 0x46, 0x52, 0x02, 0x65, 0x46, 0xfa, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9,
	0x10, 0x39, 0x29, 0x99, 0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0xfd, 0xc4, 0x82, 0x4c, 0xfd, 0xc4,
	0xbc, 0xbc, 0xfc, 0x92, 0xc4, 0x92, 0xcc, 0xfc, 0xbc, 0x62, 0x88, 0xac, 0x92, 0x1e, 0x97, 0xb0,
	0x4f, 0x66, 0x71, 0x89, 0x2f, 0x44, 0x4b, 0x71, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90,
	0x38, 0x17, 0x3b, 0xd8, 0x8a, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x36, 0x10,
	0xd7, 0x33, 0x45, 0xc9, 0x99, 0x4b, 0x04, 0x55, 0x7d, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90,
	0x36, 0x17, 0x3b, 0xd4, 0x5a, 0xb0, 0x06, 0x6e, 0x23, 0x41, 0x3d, 0x98, 0x9b, 0xf4, 0xa0, 0x8a,
	0x83, 0x60, 0x2a, 0x8c, 0x1a, 0x18, 0xb9, 0xd8, 0xdd, 0x52, 0x53, 0x53, 0x1c, 0x03, 0x3c, 0x85,
	0x4a, 0xb9, 0x78, 0x90, 0x0d, 0x14, 0x92, 0x45, 0xe8, 0xc3, 0xe2, 0x30, 0x29, 0x39, 0x5c, 0xd2,
	0x10, 0x77, 0x28, 0xa9, 0x34, 0x5d, 0x7e, 0x32, 0x99, 0x49, 0x4e, 0x48, 0x46, 0x1f, 0x1a, 0x4a,
	0xc5, 0xfa, 0xd5, 0x50, 0x9f, 0xd4, 0xc2, 0x02, 0xa6, 0xd8, 0x80, 0xd1, 0xc9, 0x95, 0x8b, 0x27,
	0x39, 0x3f, 0x17, 0x6e, 0x98, 0x13, 0x1f, 0xd8, 0x3d, 0x05, 0x99, 0x61, 0x46, 0x01, 0x20, 0xa1,
	0x00, 0xc6, 0x28, 0x76, 0xb0, 0x5c, 0x99, 0xd1, 0x22, 0x26, 0xe6, 0x80, 0x88, 0x88, 0x55, 0x4c,
	0x1c, 0x60, 0x09, 0xbd, 0x30, 0xa3, 0x53, 0x50, 0x66, 0x4c, 0x98, 0x51, 0x12, 0x1b, 0x58, 0x91,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x2e, 0xc7, 0xc3, 0x16, 0x94, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FeedAPIClient is the client API for FeedAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FeedAPIClient interface {
	ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (FeedAPI_ListMessagesClient, error)
}

type feedAPIClient struct {
	cc *grpc.ClientConn
}

func NewFeedAPIClient(cc *grpc.ClientConn) FeedAPIClient {
	return &feedAPIClient{cc}
}

func (c *feedAPIClient) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (FeedAPI_ListMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FeedAPI_serviceDesc.Streams[0], "/proto.v2.FeedAPI/ListMessages", opts...)
	if err != nil {
		return nil, err
	}
	x := &feedAPIListMessagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FeedAPI_ListMessagesClient interface {
	Recv() (*ListMessagesResponse, error)
	grpc.ClientStream
}

type feedAPIListMessagesClient struct {
	grpc.ClientStream
}

func (x *feedAPIListMessagesClient) Recv() (*ListMessagesResponse, error) {
	m := new(ListMessagesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FeedAPIServer is the server API for FeedAPI service.
type FeedAPIServer interface {
	ListMessages(*ListMessagesRequest, FeedAPI_ListMessagesServer) error
}

// UnimplementedFeedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedFeedAPIServer struct {
}

func (*UnimplementedFeedAPIServer) ListMessages(req *ListMessagesRequest, srv FeedAPI_ListMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListMessages not implemented")
}

func RegisterFeedAPIServer(s *grpc.Server, srv FeedAPIServer) {
	s.RegisterService(&_FeedAPI_serviceDesc, srv)
}

func _FeedAPI_ListMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListMessagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FeedAPIServer).ListMessages(m, &feedAPIListMessagesServer{stream})
}

type FeedAPI_ListMessagesServer interface {
	Send(*ListMessagesResponse) error
	grpc.ServerStream
}

type feedAPIListMessagesServer struct {
	grpc.ServerStream
}

func (x *feedAPIListMessagesServer) Send(m *ListMessagesResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _FeedAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v2.FeedAPI",
	HandlerType: (*FeedAPIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListMessages",
			Handler:       _FeedAPI_ListMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v2/feed_api.proto",
}
