// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: v2/feed_api.proto

/*
Package protov2 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package protov2

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/descriptor"
	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/status"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = descriptor.ForMessage

func request_FeedAPI_ListMessages_0(ctx context.Context, marshaler runtime.Marshaler, client FeedAPIClient, req *http.Request, pathParams map[string]string) (FeedAPI_ListMessagesClient, runtime.ServerMetadata, error) {
	var protoReq ListMessagesRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["feed_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "feed_id")
	}

	protoReq.FeedId, err = runtime.String(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "feed_id", err)
	}

	stream, err := client.ListMessages(ctx, &protoReq)
	if err != nil {
		return nil, metadata, err
	}
	header, err := stream.Header()
	if err != nil {
		return nil, metadata, err
	}
	metadata.HeaderMD = header
	return stream, metadata, nil

}

// RegisterFeedAPIHandlerServer registers the http handlers for service FeedAPI to "mux".
// UnaryRPC     :call FeedAPIServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
func RegisterFeedAPIHandlerServer(ctx context.Context, mux *runtime.ServeMux, server FeedAPIServer) error {

	mux.Handle("GET", pattern_FeedAPI_ListMessages_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		err := status.Error(codes.Unimplemented, "streaming calls are not yet supported in the in-process transport")
		_, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
		return
	})

	return nil
}

// RegisterFeedAPIHandlerFromEndpoint is same as RegisterFeedAPIHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterFeedAPIHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterFeedAPIHandler(ctx, mux, conn)
}

// RegisterFeedAPIHandler registers the http handlers for service FeedAPI to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterFeedAPIHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterFeedAPIHandlerClient(ctx, mux, NewFeedAPIClient(conn))
}

// RegisterFeedAPIHandlerClient registers the http handlers for service FeedAPI
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "FeedAPIClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "FeedAPIClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "FeedAPIClient" to call the correct interceptors.
func RegisterFeedAPIHandlerClient(ctx context.Context, mux *runtime.ServeMux, client FeedAPIClient) error {

	mux.Handle("GET", pattern_FeedAPI_ListMessages_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_FeedAPI_ListMessages_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_FeedAPI_ListMessages_0(ctx, mux, outboundMarshaler, w, req, func() (proto.Message, error) { return resp.Recv() }, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_FeedAPI_ListMessages_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2, 2, 3}, []string{"v2", "feeds", "feed_id", "messages"}, "", runtime.AssumeColonVerbOpt(true)))
)

var (
	forward_FeedAPI_ListMessages_0 = runtime.ForwardResponseStream
)
