// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v2/message.proto

package protov2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd63fc71f4afe6c8, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "proto.v2.Message")
}

func init() { proto.RegisterFile("v2/message.proto", fileDescriptor_dd63fc71f4afe6c8) }

var fileDescriptor_dd63fc71f4afe6c8 = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x33, 0xd2, 0xcf,
	0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53,
	0x7a, 0x65, 0x46, 0x4a, 0xb2, 0x5c, 0xec, 0xbe, 0x10, 0x29, 0x21, 0x21, 0x2e, 0x96, 0xa4, 0xfc,
	0x94, 0x4a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0xdb, 0xc9, 0x99, 0x8b, 0x27, 0x39,
	0x3f, 0x57, 0x0f, 0xa6, 0xdc, 0x89, 0x07, 0xaa, 0x38, 0x00, 0x24, 0x10, 0xc0, 0x18, 0xc5, 0x0e,
	0x96, 0x29, 0x33, 0x5a, 0xc4, 0xc4, 0x1c, 0x10, 0x11, 0xb1, 0x8a, 0x89, 0x03, 0x2c, 0xa1, 0x17,
	0x66, 0x74, 0x0a, 0xca, 0x8c, 0x09, 0x33, 0x4a, 0x62, 0x03, 0x2b, 0x32, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xf5, 0x7b, 0x58, 0x47, 0x88, 0x00, 0x00, 0x00,
}
